image: python:3.8

before_script:
    - python --version
    - pip install -e .[dev]
    - flake8 --version
    - mypy --version
    - pytest --version

test-codestyle:
  stage: test
  script:
    - pwd
    - ls -l
    - python -c "import sys;print(sys.path)"
    - flake8 --config=setup.cfg
    - mypy --config-file mypy.ini

test-units:
  stage: test
  script:
    - pwd
    - ls -l
    - python -c "import sys;print(sys.path)"
    - python -m pytest .
