default:
  image: python:3.8

build-job:
  stage: build
  script:
    - python --version
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

test-codestyle:
  stage: test
  script:
    - python -m flake8 --config=setup.cfg
    - python -m mypy --config-file mypy.ini

test-units:
  stage: test
  script:
    - pythom -m pytest .