image: python:3.7

before_script:
  - python --version
  - pip install --find-links https://download.pytorch.org/whl/torch_stable.html "torch==1.9.0+cu111" "torchvision==0.10.0+cu111"
  - pip install -e .[dev]
  - pwd
  - ls -l
  - python -c "import sys;print(sys.path)"

.codestyle:
  stage: test
  script:
    - flake8 --version
    - mypy --version
    - flake8
    - mypy --config-file mypy.ini

codestyle:
  extends: .codestyle

codestyle:3.8:
  extends: .codestyle
  image: python:3.8

.test:
  stage: test
  script:
    - pytest --version
    - python -m pytest .

test:
  extends: .test

test:3.8:
  extends: .test
  image: python:3.8

test-build-doc:
  stage: test
  script:
    - apt-get update && apt-get install -y pandoc
    - sphinx-build -b html docs/source/ docs/build/ -a
