image: python:3.7

before_script:
  - python --version
  - pip install -e ".[dev]"

.scheduled-only:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

# Checking codestyle

.codestyle:
  stage: test
  script:
    - flake8 --version
    - mypy --version
    - black --version
    - flake8
    - mypy --config-file mypy.ini
    - black . --check --verbose --diff --color

codestyle:
  extends: .codestyle

codestyle:3.10:
  extends:
    - .codestyle
    - .scheduled-only
  image: python:3.10

# Running tests

.test:
  stage: test
  script:
    - pytest --version
    - python -m pytest .

test-and-coverage:
  extends: .test
  script:
    - pytest --version
    - coverage run -m pytest
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

test:3.10:
  extends:
    - .test
    - .scheduled-only
  image: python:3.10

test:torch-compatibility:
  extends:
    - .test
  script:
    - pip install torch~=1.12.0 torchvision~=0.13.0
    - pytest --version
    - python -m pytest .

# Documentation

test-build-doc:
  stage: test
  script:
    - apt-get update && apt-get install -y pandoc
    - sphinx-build -b html docs/source/ docs/build/ -a

test-doc-completeness:
  extends: .scheduled-only
  stage: test
  script:
    - flake8 --version
    # explicitly select Docstring errors and ignore to overwrite config in setup.cfg
    - flake8 --select=D1 --ignore=E501
