build-job:
  stage: build
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

test-job1:
  stage: test
  script:
    - flake8 --config=setup.cfg
    - mypy --config-file mypy.ini

test-job2:
  stage: test
  script:
    - pytest .