image: python:3.7

before_script:
  - python --version
  - pip install -e .[dev] --extra-index-url https://download.pytorch.org/whl/cu113
  - pwd
  - ls -l
  - python -c "import sys;print(sys.path)"

.codestyle:
  stage: test
  script:
    - flake8 --version
    - mypy --version
    - black --version
    - flake8
    - mypy --config-file mypy.ini
    - black . --check --verbose --diff --color

codestyle:
  extends: .codestyle

codestyle:3.8:
  extends: .codestyle
  image: python:3.8

.test:
  stage: test
  script:
    - pytest --version
    - python -m pytest .

test:
  extends: .test

test:3.8:
  extends: .test
  image: python:3.8

test-build-doc:
  stage: test
  script:
    - apt-get update && apt-get install -y pandoc
    - sphinx-build -b html docs/source/ docs/build/ -a
